### ISSUE TITLE
Still having problems with getTime() in wmII.py

### ISSUE THREAD

**Issue by cjshaker** [jardiamj/wmII#10]
My weewx server has been crashing for a while now. Running latest updates to Raspbian Buster.
Just updated weewx to version 4.6.0-1. I ensured that I've got the latest top of branch version of wmII.py from github,
weewx gets these errors:

Feb  4 14:01:39 weather weewx[18881] INFO weewx.engine: Main loop exiting. Shutting engine down.
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__: Caught unrecoverable exception:
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****  ord() expected a character, but string of length 0 found
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 153, in main
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****      engine.run()
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 197, in run
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.PRE_LOOP))
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEv\
ent
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****      callback(event)
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 594, in pre_loop
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****      now = self.engine._get_console_time()
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 274, in _get_conso\
le_time
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****      return self.console.getTime()
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****    File "/usr/share/weewx/user/wmII.py", line 108, in getTime
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****      return self.station.get_time()
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****    File "/usr/share/weewx/user/wmII.py", line 171, in get_time
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****      sec = self.fromBCD(ord(d[2:3]))
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****  TypeError: ord() expected a character, but string of length 0 foun\
d
Feb  4 14:01:39 weather weewx[18881] CRITICAL __main__:     ****  Exiting.

I included my software version info, and a zip of the wmII.py file that I got from github, in case my git foo is bad...

[weewx_versions.txt](https://github.com/jardiamj/wmII/files/8006653/weewx_versions.txt)
[wmII.py.github.ERRORS.txt](https://github.com/jardiamj/wmII/files/8006654/wmII.py.github.ERRORS.txt)
[wmII.zip](https://github.com/jardiamj/wmII/files/8006666/wmII.zip)

Thank you,
Chris Shaker

**Comment by cjshaker** [comment]
I am running this code on a RPi4/4GB. Am wondering which RPi you are running the code on? I ask because this problem appears to be timing dependent.

I'm currently running these diffs, with wait_time set to "1.2", and it mostly works:
cjshaker@weather: cat My_Diffs
41a42,43
> wait_time = 1.5
>
89c91
<         self.loop_interval = int(stn_dict.get("loop_interval", 1))
---
>         self.loop_interval = int(stn_dict.get("loop_interval", wait_time))
167a170
>         logdbg("Attempting to get Station's Time...")
224c227
<         time.sleep(1)  # Time between consecutive calls for console to catch up
---
>         time.sleep(wait_time)  # Time between consecutive calls for console to catch up
231c234
<         time.sleep(1)  # Time between consecutive calls for console to catch up
---
>         time.sleep(wait_time)  # Time between consecutive calls for console to catch up
cjshaker@weather:

I still get occasional errors like this:
Feb  5 15:46:41 weather weewx[4915] INFO user.wmII: Weather Monitor II: Failed attempt 1 of 5 to get readings: Acknowledge returned empty: b''

Thank you,
Chris Shaker

**Comment by cjshaker** [comment]
I see that pasting my diffs into this did NOT work as I expected. Here they are as a text file:

[My_Diffs.txt](https://github.com/jardiamj/wmII/files/8009133/My_Diffs.txt)

Chris Shaker

**Comment by cjshaker** [comment]
If I set wait time between 1.2 and 1.5, the driver appears to work on my RPi4. If I set the wait time to 2.0, it fails almost immediately:
cjshaker@weather: sudo service weewx status
● weewx.service - LSB: weewx weather system
   Loaded: loaded (/etc/init.d/weewx; generated)
   Active: active (running) since Sat 2022-02-05 15:54:25 PST; 28s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5157 ExecStart=/etc/init.d/weewx start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/weewx.service
           └─5173 python3 /usr/share/weewx/weewxd --daemon --pidfile=/var/run/weewx.pid /etc/weewx/weewx.conf

Feb 05 15:54:25 weather python3[5173]: weewx[5173] INFO weewx.engine: 'pyephem' detected, extended almanac data is ava
Feb 05 15:54:25 weather python3[5173]: weewx[5173] INFO __main__: Starting up weewx version 4.6.0
Feb 05 15:54:26 weather python3[5173]: weewx[5173] INFO weewx.engine: Clock error is -5.66 seconds (positive is fast)
Feb 05 15:54:33 weather python3[5173]: weewx[5173] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sd
Feb 05 15:54:33 weather python3[5173]: weewx[5173] INFO weewx.manager: Starting backfill of daily summaries
Feb 05 15:54:33 weather python3[5173]: weewx[5173] INFO weewx.manager: Daily summaries up to date
Feb 05 15:54:33 weather python3[5173]: weewx[5173] INFO weewx.engine: Starting main packet loop.
Feb 05 15:54:35 weather python3[5173]: weewx[5173] INFO weewx.engine: Main loop exiting. Shutting engine down.
Feb 05 15:54:35 weather python3[5173]: weewx[5173] CRITICAL __main__: Caught WeeWxIOError: Acknowledge returned empty:
Feb 05 15:54:35 weather python3[5173]: weewx[5173] CRITICAL __main__:     ****  Waiting 60 seconds then retrying...
lines 1-19/19 (END)


From /var/log/syslog:
Feb  5 15:55:41 weather weewx[5173] INFO weewx.engine: Starting main packet loop.
Feb  5 15:55:44 weather weewx[5173] INFO weewx.engine: Main loop exiting. Shutting engine down.
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__: Caught unrecoverable exception:
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****  ord() expected a character, but string of length 0 found
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 153, in main
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****      engine.run()
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 197, in run
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.PRE_LOOP))
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****      callback(event)
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 594, in pre_loop
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****      now = self.engine._get_console_time()
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 274, in _get_console_time
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****      return self.console.getTime()
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****    File "/usr/share/weewx/user/wmII.py", line 110, in getTime
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****      return self.station.get_time()
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****    File "/usr/share/weewx/user/wmII.py", line 174, in get_time
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****      sec = self.fromBCD(ord(d[2:3]))
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****  TypeError: ord() expected a character, but string of length 0 found
Feb  5 15:55:44 weather weewx[5173] CRITICAL __main__:     ****  Exiting.

Am I dealing with some kind of race condition?
Chris Shaker

**Comment by cjshaker** [comment]
It appears to always crash while reading the seconds in get_time(). It appears that it successfully read the hour and minute, and then gets back a 0 while reading the seconds?
Chris Shaker

**Comment by cjshaker** [comment]
Or, am I dealing with bad hardware? I shut down the RPi4, moved the uSD card to an RPi3. Unplugged the logging device/serial interface and power from the Davis weather station display, reconnected them both, and it is working fine right now on the RPi3.

The only error it got (once) was:
Feb  6 11:58:13 weather weewx[1385] INFO weewx.engine: Error reading time: Acknowledge not equal 6: \
\
b'!'

Chris Shaker

**Comment by cjshaker** [comment]
I shut down the RPi3. Moved the uSD card back to the RPi4. Re-installed the RPi4, and weewx failed right away:
Feb  6 12:36:56 weather weewx[1457] INFO weewx.manager: Starting backfill of daily summaries
Feb  6 12:36:56 weather weewx[1457] INFO weewx.manager: Daily summaries up to date
Feb  6 12:36:56 weather weewx[1457] INFO weewx.engine: Starting main packet loop.
Feb  6 12:36:59 weather weewx[1457] INFO weewx.engine: Main loop exiting. Shutting engine down.
Feb  6 12:36:59 weather weewx[1457] DEBUG weewx.restx: Shut down AWEKAS thread.
Feb  6 12:36:59 weather weewx[1457] DEBUG weewx.restx: Shut down CWOP thread.
Feb  6 12:36:59 weather weewx[1457] DEBUG weewx.restx: Shut down PWSWeather thread.
Feb  6 12:36:59 weather weewx[1457] DEBUG weewx.restx: Shut down Wunderground-RF thread.
Feb  6 12:36:59 weather weewx[1457] DEBUG weewx.restx: Shut down StationRegistry thread.
Feb  6 12:36:59 weather weewx[1457] DEBUG user.wmII: Weather Monitor II: close serial port /dev/ttyUSB0
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__: Caught unrecoverable exception:
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****  ord() expected a character, but string of length 0 found
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 153, in main
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****      engine.run()
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 197, in run
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.PRE_LOOP))
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****      callback(event)
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 594, in pre_loop
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****      now = self.engine._get_console_time()
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 274, in _get_console_time
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****      return self.console.getTime()
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****    File "/usr/share/weewx/user/wmII.py", line 108, in getTime
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****      return self.station.get_time()
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****    File "/usr/share/weewx/user/wmII.py", line 169, in get_time
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****      hour = self.fromBCD(ord(d[0:1]))
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****  TypeError: ord() expected a character, but string of length 0 found
Feb  6 12:36:59 weather weewx[1457] CRITICAL __main__:     ****  Exiting.


This is while running the current code from github.
Chris Shaker

**Comment by cjshaker** [comment]
Currently successfully running the github code on the RPi4 with one functional difference - changed self.timeout on serial port from 2 to 5.0 seconds. I also changed self.retry_wait from 3 to 3.0 seconds. The timeout values are floats. Wondering why these shouldn't both be controlled from a constant?

So far, with these diffs on the RPi4, the system and weewx have been up for 44 minutes with NO errors at all.

[My_new_diffs.txt](https://github.com/jardiamj/wmII/files/8011230/My_new_diffs.txt)

Chris Shaker

**Comment by cjshaker** [comment]
With those small changes, weewx has been running on the RPi4 for 1:41 now, with NO errors at all.
Chris Shaker

**Comment by jardiamj** [comment]
Sorry my lack of response on the issue, I have been a bit busy these days. Thanks for all the debugging you have done, and for finding a solution. I am running my weewx server on a old Acer Apire One netbook, it does this task quite well; it's been running with this driver for a few years, most of the current issues that people have been reporting tend to be related to the migration to Python 3.

As to why those timeouts are not controlled from a constant, it's because I am not sure if Python supports constants. If you can submit a PR, I will gladly merge your changes; otherwise, I will update it myself in a couple of days.

BTW, I am still amazed that others are using this driver. How old is your Weather Station? It seems like they are quite durable.

**Comment by cjshaker** [comment]
Jardi:

Thank you very much for writing this device driver!

It's now been running for over 5 1/2 hrs with NO errors. I think this is the fix.

I've been carting this hardware around for years after receiving it as a gift. Finally installed it at this house a couple of years ago.

I've been using this exercise to learn a bit about Python. I was a C coder, microcoder, and assembly coder on embedded systems.

Thank you again!
Chris Shaker

**Comment by cjshaker** [comment]
Jardi:

Woke up this morning realizing that the root cause is most likely the kernel timing routines for the various Raspberry Pis. I'm wondering how much testing they have had, to ensure that a two second timeout is the same on all models?

Also, it appears that you are correct that Python does not have constants:
"Note: In reality, we don't use constants in Python. Naming them in all capital letters is a convention to separate them from variables, however, it does not actually prevent reassignment."
https://www.programiz.com/python-programming/variables-constants-literals

Chris Shaker
