### ISSUE TITLE
So far so good , except indoor humidity

### ISSUE THREAD

**Issue by bill-orange** [jardiamj/wmII#3]
Like you, I acquired a used Monitor II station gratis.  Thank you for the driver and especially for the installation instructions. Once I realized that my Prolific serial to USB cable was not assigned to /dev/ttyUSBx without a reboot, I was up and running. 

I have had one incident of out of bounds humidity as was reported in the prior post. I rebooted the PI and it has not reoccurred. I will reply to that post if I get more information. 

The only remaining problem is a hardware issue. The indoor humidity sensor is off by about 50%. It does respond to changes in the environment so it’s not totally shot but I would rather replace the sensor than try to adjust out the error.

Have you run across any schematics or parts lists for the monitor II? I looked around online without success.

**Comment by jardiamj** [comment]
Hi Bill, I am glad this driver is being of some use. I don't remembering encountering any schematics of the monitor II console, I did a lot of research on the serial communication protocol when I decided to get on the task of developing the driver but I didn't do much research on the hardware side of the station.
No long ago when someone reported some very odd out of range data I did some googling but I didn't find much. I found this little article about some old Davis models, but it isn't of much help: https://www.manula.com/manuals/pws/davis-kb/1/en/topic/older-davis-stations
I will see if I can get some time this week to take apart the console and investigate to see if I can identify the type of humidity and temperature sensors being used.

**Comment by bill-orange** [comment]
Thank you!  Since my post I discovered the identify of the sensor. It is a capacitive Phillips sensor still available at Digikey. Examination of the board revealed that the nearby 10 turn 50k pot was the calibration adjustment   Oddly is was pegged against one stop. I adjusted it to agree with one of my BME280 sensors. The sensor read correctly about 5 turns in. No one had messed with the thing. The warranty seal was a intact. I wonder if Davis failed to set the pot at the factory. We will likely never know. 

In any case, your driver is working fine and all sensor appear to be functioning okay. 

Thanks again. I

**Comment by JayBee103** [comment]
I too encountered the humidity out of bounds issue on the wmii. Upon
comparing the readings over time, with adjacent weather stations I came to
the conclusion my humidity readings were high. I adjusted them using the
adjustment features in weewx conf file. I've not had a recurrence, and find
them to track better with other local weather stations. I do not know if
this is the same issue you are experiencing.

If you upload your data to other weather services (like awekas) they can
automatically do some of those comparisons

The other issue I am still troubleshooting is a noisy line.

I get quite a few retrys pulling the serial data, and after enough of them
it restarts and I have small gaps in my data. Some times it will run for
days. Other times not for an hour. Not sure if a hardware, software,
cooling or environmental issue.

I was out of town for a week, and it died shortly after I left.

Http://weather.jimbrand.net


Jim

**Comment by bill-orange** [comment]
@JayBee103 I have also experienced instability in both weewx and wview.  I have never nailed dwon the cause.  What I am doing now is a scheduled reboot at midnight.  That seems to do the trick (mostly).
`sudo apt-get install gnome-schedule`

Here's my current wview station.  I am thinking of switch to the old monitor II since despite its age, it is so much better built than the Acu-rite.

http://orangecaweather.duckdns.org/weather/

**Comment by jardiamj** [comment]
@bill-orange. Awesome that you could calibrate the sensor with a few turns to the 50K pot, can you give us more info on the capacitive phillips humidity sensor? somebody else could benefit from it.
@JayBee103. My WeeWX instance has been running for months without any issues, what I noticed when I was writing the driver is that if the console is busy doing something else while WeeWX is getting Loop packets it will fail. Even a few button presses on the console to change the screen information might cause it to fail, that's why I implemented the ```get_readings_with_retry``` so the driver doesn't crash altogether.
You might also want to check the usb connection and the logger connection to the console, as I said, mine has been running with this driver non-stop for months.
Lastly, what's in the logs when it crashes?

**Comment by bill-orange** [comment]
Here's the sensor:

https://media.digikey.com/pdf/Data%20Sheets/BC%20Components%20PDFs/2322%20691%2090001.pdf

Vishay must have bought the product line back in the day.

**Comment by bill-orange** [comment]
I will have to check the log in the next incident. I believe the crashes are outside of weewx. The appear to be on the PI side of things.
