### ISSUE TITLE
Anomaly in Wunderground Post

### ISSUE THREAD

**Issue by bill-orange** [jardiamj/wmII#4]
This is a perplexing problem.  I don't know enough about the structure of weewx code or the Davis Monitor II driver to hazard a guess as to which nay be the problem.  My station, a Davis Monitor II, running on a Raspberry PI B+ appears to be working fine without drama.  The PI has an IP assigned outside of DHCP on a Spectrum Gateway router. I have always had stability issues between PIs and Spectrum.  I have avoided the random disconnects by running this on the hour as a chron task.

```
#!/bin/bash
sudo ifconfig wlan0 down
sudo ifconfig wlan0 up
sudo service networking restart
```
 
 I let the setup run several days before enabling posting to Wundergound.  My data when views on the web site locally looked fine.  When I looked at my data on WundergroundI discovered an anomaly with humidity.  After the chron task ran the pressure reads low for one reading.

![Wu_report](https://user-images.githubusercontent.com/18121312/64119922-cbfd5b00-cd4f-11e9-9f46-467b725aeb9e.jpg)

This is beyond weird. Only pressure is off and it is only the first reading after the network reconnect.  What could be wrong?  Have I discovered some really subtle bug?  If you think so, I can repost on the weewx google development forum.

Bill - AB6OR

** EDIT

Reply from the Google forum:

Looking at KCAORANG21, the WU is receiving low values for pressure on the hour, although with the WU, you never really know. But, given that you are cycling the wifi adapter at exactly the same time, odds are that the problem is on your end, rather than on the WU end.

I am not familiar with the wmii driver but, looking through its code, it ignores the checksum, so it's entirely possible it is receiving a bad packet on the hour, which gets decoded into nonsense values. The many bad values logged give evidence to this theory. For example,

Sep  1 08:29:17 raspberrypi weewx[425]: engine: 2019-09-01 08:29:17 PDT (1567351757) LOOP value 'pressure' -29.33 outside limits (24.0, 34.5)
Sep  1 08:29:17 raspberrypi weewx[425]: engine: 2019-09-01 08:29:17 PDT (1567351757) LOOP value 'outHumidity' 128 outside limits (0.0, 100.0)
Sep  1 08:29:17 raspberrypi weewx[425]: engine: 2019-09-01 08:29:17 PDT (1567351757) LOOP value 'outTemp' 3276.7 outside limits (-40.0, 120.0)
Sep  1 08:29:18 raspberrypi weewx[425]: engine: 2019-09-01 08:29:18 PDT (1567351758) LOOP value 'pressure' -29.33 outside limits (24.0, 34.5)
Sep  1 08:29:18 raspberrypi weewx[425]: engine: 2019-09-01 08:29:18 PDT (1567351758) LOOP value 'outHumidity' 128 outside limits (0.0, 100.0)

So, when weewx calculates the average pressure for the interval, it gets an off value. Incidentally, you're getting low values for other types, such as outside temperature. They are probably suffering from the same problem.

*********

I will be happy to work on the code if you can point me in the right direction.  It looks to be like you are using CRC but perhaps the wrong thing is happening if a bad CRC is discovered.

**Comment by jardiamj** [comment]
Hi Bill,
The CRC is actually checked in the code lines 252-253:
```
if weewx.crc16.crc16(buf): #CRC_checksum
    raise weewx.WeeWxIOError("CRC Checksum error")
```
It looks to me like your station's Temperature, Humidity and Pressure sensors throw some bad values every so often. I wonder if there is some loose connection somewhere, as to why the data uploaded to WU is showing that pattern I don't really have a clue but I don't think the wmII driver has anything to do with it. I think It's more likely related to your restarting of your internet connection every hour.

**Comment by bill-orange** [comment]
I changed RS-232/USB cables to one using a different chip.  I will see if that helps.   Do you think lowering the baud rate to 1200 on the device and the driver might help?  I recrimpted the connector on the data logger "just in case".  That's about the only connector that could be a problem, since temperature and pressure are affected.  Temp is external and pressure is internal to the station.

I am still confused on  how CRC is implemented in the driver.  In lines 294 to 305 I don't see the CRC checksum being collected for later comparison to the calculated value.  It looks like `weewx.crc16.crc16(buf)` returns the CRC bytes and passes without an error reported if non zero.  I don't see the comparison being made to CRC_checksum.   It just passes the test if non zero.

Perhaps we need up around 304 `data['CRC_checksum'] = buf[11]`  and later 252 would be something like 

`if (weewx.crc16.crc16(buf) != weewx.CRC_checksum): #CRC_checksum comparison`

I am not sure about that last part , data['CRC_checksum']  doesn't look global so the data would have to come back from weewx.  I don't understand how weewx drivers are constructed so I could be completely wrong.

Another question; loop_interval is now 1. Should it perhaps be longer?

Sorry to be a pest and thanks for all the help.

**Comment by jardiamj** [comment]
The implementation for the CRC checksum is in the weewx core already, so the driver is just relying on that implementation. The crc16 function should return 0 (zero) if the checksum is correct, so any non-zero value would give us a "CRC checksum error".

This is what the WMII documentation says about doing the CRC Checking:

- F. CRC Checking
     The CRC checking used by the WeatherLink is based on the CRC-CCITT standard. The heart of the method involves a CRC-accumulator that uses the following formula on each successive data byte. After all the data bytes have been "accumulated", there will be a two byte CRC checksum that will get processed in the same manner as the data bytes. If there has been no transmission error, then the final CRC-accumulator value will be 0 (assuming it was set to zero before accumulating data).

I agree in that the loop_interval should be longer, you can change that in the weewx.conf file, I think I had it that short when I was testing the driver but I made it longer in my weewx instance.

I have a few technical reference files, I found online for the WMII,  that I used for developing the driver. If you want them I can put then in a zipped tarball and email them to you.

Not a pest at all, I am here to help and maybe the driver has bugs that need to be iron out. In fact I am going to go over it this weekend and clean some things up.

**Comment by bill-orange** [comment]
Yes, indeed please send me the reference material!

Bill
