### ISSUE TITLE
error message pass through

### ISSUE THREAD

**Issue by bill-orange** [jardiamj/wmII#5]
Occasionally, I have trouble getting up and running on a reboot.   I checked the syslog for errors and did not find a smoking gun.  Weewx shut down when the driver was on failure 3 of 5.  Not sure why.  I did notice this somewhat unrelated issue.  The log shows this:

Sep 12 00:01:02 raspberrypi weewx[423]:     ****      syslog.syslog(level, 'Weather Monitor II: %s' % msg)
Sep 12 00:01:02 raspberrypi weewx[423]:     ****  TypeError: [priority,] message string
Sep 12 00:01:02 raspberrypi weewx[423]:     ****  Exiting.

My python is rusty.  Is line line okay in the driver?

`39    syslog.syslog(level, 'Weather Monitor II: %s' % msg)`

The second % looks misplaced.

P.S. I am working on other issues right now.  I am a ham.  If I transmit on 20m at 100 watts.  I get bad data from the weather station.  RF is being picked up and rectified by the humidity/temp sensor.  Adding Ferrite to cable is helping.  I have added some small caps to a spare humidity/temp sensor board and I eant to see if that helps.  Here's my station:

(https://www.wunderground.com/dashboard/pws/KCAORANG21?cm_ven=localwx_pwsdash)

**Comment by jardiamj** [comment]
Can you post a little more of that log? I can't figure out what's braking the syslog.

**Comment by bill-orange** [comment]
Here you go!
[abridged_syslog.txt](https://github.com/jardiamj/wmII/files/3607735/abridged_syslog.txt)

**Comment by jardiamj** [comment]
Hi Bill,

This error is a bit puzzling, the exception that makes weewx crash seems to be happening in the ```get_readings_with_retry()``` function. It seems to be a problem with your USB adapter throwing an error that the syslog module fails to catch.

I think the issue has to do with this line:
```Sep 12 00:01:02 raspberrypi kernel: [   48.792401] pl2303 ttyUSB0: error sending break = -32```

The way I read it is: The driver gets a loop response that is shorter that the expected 17 bits so it retries and sends another LOOP command through the serial port, then in the 2nd attempt it gets a loop response with the wrong acknowledge so it retries again but this time the LOOP command fails to be sent due to some connection issues with your USB adapter. I would try with a different adapter and see if that fixes the issue.

```
Sep 12 00:00:52 raspberrypi weewx[423]: Weather Monitor II: Failed attempt 1 of 5 to get readings: Invalid Lenght of Loop response: len 2
Sep 12 00:00:55 raspberrypi weewx[423]: Weather Monitor II: Failed attempt 2 of 5 to get readings: Acknowledge not equal 6: 
Sep 12 00:00:57 raspberrypi colord[413]: failed to get session [pid 298]: No data available
Sep 12 00:00:58 raspberrypi weewx[423]: Weather Monitor II: Failed attempt 3 of 5 to get readings: Acknowledge not equal 6: #002
Sep 12 00:01:00 raspberrypi systemd[1]: systemd-hostnamed.service: Succeeded.
Sep 12 00:01:01 raspberrypi weewx[423]: engine: Main loop exiting. Shutting engine down.
Sep 12 00:01:02 raspberrypi weewx[423]: engine: Caught unrecoverable exception in engine:
Sep 12 00:01:02 raspberrypi weewx[423]:     ****  [priority,] message string
Sep 12 00:01:02 raspberrypi kernel: [   48.792401] pl2303 ttyUSB0: error sending break = -32
Sep 12 00:01:02 raspberrypi weewx[423]:     ****  Traceback (most recent call last):
```

**Comment by bill-orange** [comment]
I have two cables, each using a different chip. I will try the other one. At worst, I can go down to MicroCenter and buy one of the pricy name brand cables. 

Thanks.

**Comment by wjs33** [comment]
I have same problem....and test with 3 different cables , but without solution....Question: If connect WMII to GPIO Serial port, will communicate good?...Thanks

**Comment by bill-orange** [comment]
I don't know what software changes you would need to use GPIO Serial,  In my case using GPIO Serial rather than a USB adapter probably would not have helped.  RF was getting into the weather station on the cable from the wind speed/direction sensor.  the solution was to put half a dozen cable style ferrite blocks on the cable at the sensor side.
