### ISSUE TITLE
Compile fails under Python3 / weewx 4.5.1

### ISSUE THREAD

**Issue by cube1us** [jardiamj/wmII#7]
Jun  1 17:38:59 mythtv2 weewx[9067] CRITICAL __main__:     ****    File "/opt/weewx/bin/user/wmII.py", line 198, in ReadWRD
Jun  1 17:38:59 mythtv2 weewx[9067] CRITICAL __main__:     ****      b'WRD' + chr((n << 4) | bankval) + chr(addr & 0x00FF) + chr(0xD)
Jun  1 17:38:59 mythtv2 weewx[9067] CRITICAL __main__:     ****  TypeError: can't concat str to bytes

I will post a "diff" if I can fix it (I expect I will be able tod)

**Comment by jardiamj** [comment]
Try substituting `b'WRD'` with `'WRD'.encode()`. I believe that should do the trick in python 3.

**Comment by cube1us** [comment]
It is a bit worse than I thought.  I have code that handles receiving 
data fine (see below) and I tested it using the "self test" code at the 
bottom of the module, but it will break inside method WriteWRD, which 
sometimes receives type "bytes" (from WriteWord when it uses 
struct.pack()) and sometimes a string (when called directly using 
concatenations of chr() ).  As I coded it WriteWRD uses data.encode() 
which will fail when passed a byte string from WriteWORD.

(The test mode code you put in doesn't exercise that part because it 
never calls set_time(), but I got a little suspicious and investigated 
further).

This bit of interactive work illustrates the issue:
 >>> import struct
 >>> #  Typical of call to WriteWord
 >>> mybytes = struct.pack("<h",0x1da)    >>> print(mybytes)
b'\xda\x01'

 >>> # As I currently have WriteWRD coded when called from WriteWord
 >>> print(mybytes.encode('utf-8'))
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
AttributeError: 'bytes' object has no attribute 'encode'

 >>> # Typical of direct call to WriteWRD
 >>> mystring = chr(0x17) + chr(0x55) + chr(0x59)
 >>> print(mystring)
↨UY

 >>> # The plan: add a .encode() to those cases yielding bytes
 >>> mystringbytes = mystring.encode('utf-8')
 >>> print(mystringbytes)
b'\x17UY'

 >>> # This shows the original issue
 >>> print(b'WWR' + mystring)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
TypeError: can't concat str to bytes
 >>> print(b'WWR' + mystring.encode('utf-8'))
b'WWR\x17UY'
 >>> print(b'WWR' + mybytes.encode('utf-8'))
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
AttributeError: 'bytes' object has no attribute 'encode'
 >>> print(b'WWR' + mybytes)
b'WWR\xda\x01'
 >>>

Here is the code as I now have it - which works OK under test, but, as I 
said, will fail in method set_time()

This difference handles receiving fine, but like I said, I have a bit 
more work to do.  I think I will have WriteWRD expect the "bytes" type 
(and thus concatenate, as it does now), but change the calls to it that 
use concatenated strings to convert them to "bytes" using 
.encode('utf-8').  That *should* work.

8a9,15
 > #
 > #     Adapted for Python3 Jay R. Jaeger  ***@***.*** June, 2021
 > #
 > #     Note:  I left ord(single-byte-value), though strictly speaking
 > #     it should probably be done as int(single-byte-value)
 > #
 >
197,199c204,208
<         self.serial_port.write(
<             b'WRD' + chr((n << 4) | bankval) + chr(addr & 0x00FF) + 
chr(0xD)
<         )
---
 > #        self.serial_port.write(
 > #            b'WRD' + chr((n << 4) | bankval) + chr(addr & 0x00FF) + 
chr(0xD)
 > #        )
 >         self.serial_port.write(b'WRD' + ((n << 4) | 
bankval).to_bytes(1) +
 >            (addr & 0x00ff).to_bytes(1) + b'\r')
227,229c236,240
<         self.serial_port.write(
<             b'WWR' + chr((bankval) | (n << 4)) + chr(addr & 0x00FF) + 
data + chr(0xD)
<         )
---
 > #        self.serial_port.write(
 > #            b'WWR' + chr((bankval) | (n << 4)) + chr(addr & 0x00FF) 
+ data + chr(0xD)
 > #        )
 >         self.serial_port.write(b'WWR' + ((n << 4) | 
bankval).to_bytes(1) +
 >            (addr & 0x00ff).to_bytes(1) + data.encode('utf-8') + b'\r')
233c244,245
<         self.serial_port.write(b'START' + chr(0x0D))
---
 >         # self.serial_port.write(b'START' + chr(0x0D))
 >         self.serial_port.write(b'START\r')
237c249,250
<         self.serial_port.write(b'LOOP' + chr(255) + chr(255) + chr(0x0D))
---
 >         # self.serial_port.write(b'LOOP' + chr(255) + chr(255) + 
chr(0x0D))
 >         self.serial_port.write(b'LOOP\xff\xff\r')

**Comment by cube1us** [comment]
Attached is a version of wmII.py adjusted to work with Python 3 and 
weewx 4 (tested on weewx 4.5.1).  All of those changes were necessary - 
there were some more I could have made where there is usage of 
ord(byte-value) which is contrary to Python 3 doc - which which does 
work - that perhaps might be better coded as int(byte-value).

I will *not* be maintaining this, as I am in the process of converting 
to a Vantage Vue - but wanted my wmII working under version 4 before I 
tackled the Davis WeatherLinkLive driver, which is also "user provided" 
on github.

JRJ

**Comment by cjshaker** [comment]
It appears that GitHub might have removed your attachment from this email?
Thank you,
Chris Shaker

**Comment by jardiamj** [comment]
As Chris mentioned, there was no attachment in the email. It would be great if I can get your new version to incorporate those changes into this repo.

**Comment by cube1us** [comment]
On my queue.  ;)

JRJ

**Comment by cube1us** [comment]
Ah - I didn't realize I could just attach it here.  Here you go!  (As a text file)

[wmII.txt](https://github.com/jardiamj/wmII/files/6604914/wmII.txt)

**Comment by jardiamj** [comment]
@cube1us. Thanks for providing the file, passing the values as bytes was definitely the way to go. Also thanks for adding the extra tests for getting and setting the time.
I patched the driver in a new branch named python3, I still need to test that it works as expected before I merge it with main.

Thanks again!

**Comment by jardiamj** [comment]
@cube1us. Tested and merged your changes into the main branch.

Thanks.
